### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by PaPaPaulitos** [ollama/ollama-js#144] opened 2024-09-18 22:03 UTC
I'm doing a project with Ollama and I'm getting an error that after 5 minutes the Ollama js library drops the request, and I use this same Ollama server in my own chat and it has never given this session expiration error.

```bash
Error generating article: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at async post (/home/paulitos/Documentos/ab-prompter/node_modules/ollama/dist/shared/ollama.9c897541.cjs:114:20)
    at async Ollama.processStreamableRequest (/home/paulitos/Documentos/ab-prompter/node_modules/ollama/dist/shared/ollama.9c897541.cjs:253:22)
    at async generateArticleWithLLM (/home/paulitos/Documentos/ab-prompter/src/application/articleUseCases.ts:23:30)
    at async fullArticleGeneratedByLLM (/home/paulitos/Documentos/ab-prompter/src/application/articleUseCases.ts:67:21)
    at async /home/paulitos/Documentos/ab-prompter/src/controllers/routerController.ts:46:22
    at async bodyParser (/home/paulitos/Documentos/ab-prompter/node_modules/koa-bodyparser/index.js:78:5) {
  [cause]: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:5995:32)
      at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:2356:17)
      at listOnTimeout (node:internal/timers:594:17)
      at processTimers (node:internal/timers:529:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
Error generating full article: Error: fetch failed
    at generateArticleWithLLM (/home/paulitos/Documentos/ab-prompter/src/application/articleUseCases.ts:50:11)
    at async fullArticleGeneratedByLLM (/home/paulitos/Documentos/ab-prompter/src/application/articleUseCases.ts:67:21)
    at async /home/paulitos/Documentos/ab-prompter/src/controllers/routerController.ts:46:22
    at async bodyParser (/home/paulitos/Documentos/ab-prompter/node_modules/koa-bodyparser/index.js:78:5)
Error generating full article: Error: fetch failed
    at fullArticleGeneratedByLLM (/home/paulitos/Documentos/ab-prompter/src/application/articleUseCases.ts:79:11)
    at async /home/paulitos/Documentos/ab-prompter/src/controllers/routerController.ts:46:22
    at async bodyParser (/home/paulitos/Documentos/ab-prompter/node_modules/koa-bodyparser/index.js:78:5)
```

**Comment by hopperelec** [comment] 2024-09-20 15:19
Looks like a duplicate of https://github.com/ollama/ollama-js/issues/103

**Comment by ParthSareen** [comment] 2024-11-07 22:59
See #103

As well as the resolution from server side: https://github.com/ollama/ollama/issues/5081#issuecomment-2458513769

**Closed by ParthSareen** 2024-11-07 22:59 UTC
