### ISSUE TITLE
JSON mode fails with "Expected a Completed Response"

### ISSUE THREAD

**Issue by meni3a** [ollama/ollama-js#82] opened 2024-05-05 13:46 UTC
Code:
```js
import ollama from 'ollama'

const response = await ollama.chat({
  model: 'llama3:8b',
  format: 'json',
  messages: [{ role: 'user', content: 'What color is the sky at different times of the day? Respond using a JSON' }],
})
console.log(response.message.content)
```
Error:
```
     throw new Error("Expected a completed response.");
              ^

Error: Expected a completed response.
    at Ollama.processStreamableRequest 
```

When I remove the `format: 'json'` everything works as expected.

**Comment by Pixelycia** [comment] 2024-05-06 19:56
Sometimes small LLMs struggle to provide a proper JSON, especially when you ask just "give me a JSON" without further instructions. Try to provide in a request some examples:

```
What color is the sky at different times of the day? Respond using a JSON.

Response example: 
{
   "morning": color_a,
   "day": color_b,
   "evening": color_c
}
```

Read about some prompt techniques here https://www.promptingguide.ai/techniques/fewshot (just dropped a random link from the internet).

For single request tasks try to use `ollama.generate` and modify the `system` property, to try to instruct model behave in a more restricted way, with the temperature of 0.

**Comment by meni3a** [comment] 2024-05-07 10:46
@Pixelycia Thanks for responding.
In this case, it doesn't seem the issue is with the model itself. Using the Ollama API, the model works as expected.
for example:
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama3-gradient",
  "prompt": "What color is the sky at different times of the day? Respond using JSON",
  "format": "json",
  "stream": false
}'
```
Result:
```json
{
    "model": "llama3-gradient",
    "created_at": "2024-05-07T10:36:49.427165Z",
    "response": "{ \"morning\": \"Light blue\",\n\"daytime\": \"Bright blue\",\n\"afternoon\": \"Golden yellow\",\n\"evening\": \"Orange\",\n\"night\": \"Dark purple\"} ",
    "done": false
}
```

Only when I use the ollama-js I get the error I mentioned above: "**Expected a Completed Response"**.

**Comment by Pixelycia** [comment] 2024-05-07 12:42
Just double checked, with a few-shot prompt like this:
```
What color is the sky at different times of the day? Respond using JSON format.
Response example: 
{
  date_time: color_a,
}
```
I got a valid JSON response with `{ "format": "json" }`:
```
{
    "sunrise": "pinkish-orange",
    "morning": "blue",
    "afternoon": "slightly hazy blue",
    "evening": "reddish-purple",
    "night": "black"
}
```

**Comment by Pixelycia** [comment] 2024-05-07 13:01
Another cool suggestion - try to avoid JSON, because usually LLM god in python, try to ask: `What color is the sky at different times of the day? Respond using python dictionary format.`, it usually performs MUCH better.

**Comment by meni3a** [comment] 2024-05-08 07:06
@Pixelycia 
It's indeed possible to solve this with a little bit of code engineering. but I'm trying to take advantage of `format: 'json'` option of Ollama. 
every time I put `format: 'json'` in my ollama-js project I get an error, and when I use it directly in the model through the CLI or the API - I get the response successfully.
it's the same exact model instance (running on my local machine) with the exact same prompt. 
I tried it many times and got the same results. I don't think it is related to LLM not being consistent.. it looks like some an issue with ollama-js.

**Comment by meni3a** [comment] 2024-05-08 10:56
I cloned ollama-js and deleted line 92 in the browser.ts file:
```ts
throw new Error('Expected a completed response.')
```
**And now it works perfectly.**

it seems like there is an issue with the condition when using `format: 'json'`.

@samwillis I would appreciate it if you could look at this part of the code:
src/browser.ts in `processStreamableRequest` method line 92
```ts
 if (!message.value.done && (message.value as any).status !== 'success') {
     throw new Error('Expected a completed response.')
 }
```
I see that `message.value.done` always equals `false` in json format.

**Comment by ManikantaMandala** [comment] 2024-10-07 16:17
Hey @meni3a @BruceMacD I have checked the above mentioned case and It works!
and also the suggested line 92 doesn't have the code mentioned above

**Comment by ParthSareen** [comment] 2024-11-07 23:22
Tried to reproduce with the original code above - I don't think we are checking for this condition anymore - going to close this issue out unless someone. Thanks @ManikantaMandala!

**Closed by ParthSareen** 2024-11-07 23:22 UTC
